// index.tsからいい感じにしていく
// 	routerを作ってみる//
// 	middleware的なのをまとめる//
// 	DBconnectionを貼ってみる
// 		DBを扱えるクラスを作ってみる
// 			まずは抽象クラスから
// 		その中に入れる
// 	controllerを作ってみる
// 		classをとりあえず書く
// 実際にエンドポイント書いてみる
// 	read
// 	create
// 	update
// 	done
// 	delete
